### ISSUE TITLE
Actions for Relations - only one action is visible

### ISSUE THREAD

**Issue by pigreco** [opengisch/qgis-actions-for-relations#3]
Even if I define multiple actions, only the first action appears in the context menus

![image](https://user-images.githubusercontent.com/7631137/101507017-62b6bf80-3976-11eb-9570-4e8630823dd4.png)

Aggregate actions

![image](https://user-images.githubusercontent.com/7631137/101507201-98f43f00-3976-11eb-8af4-0cca77034b0c.png)

**Comment by 3nids** [comment]
thanks for reporting, this is fixed.
